// web/src/components/dialogs/base/Dialog.jsx
import React, { Fragment } from 'react'
import { Transition, Dialog as HDialog } from '@headlessui/react'

export default function Dialog({ isOpen, setIsOpen, children }) {
  return (
    <Transition show={isOpen} as={Fragment}>
      <HDialog open={isOpen} onClose={setIsOpen} static>
        <div className="fixed z-10 inset-0 overflow-y-auto">
          <div className="flex items-end justify-center min-h-screen pt-4 px-4 pb-20 text-center sm:block sm:p-0">
            <Transition.Child
              enter="ease-out duration-300"
              enterFrom="opacity-0"
              enterTo="opacity-100"
              leave="ease-in duration-200"
              leaveFrom="opacity-100"
              leaveTo="opacity-0"
            >
              <HDialog.Overlay className="fixed inset-0 transition-opacity">
                <div className="absolute inset-0 bg-gray-500 opacity-75" />
              </HDialog.Overlay>
            </Transition.Child>

            <Transition.Child
              enter="ease-out transform duration-300"
              enterFrom="opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
              enterTo="opacity-100 translate-y-0 sm:scale-100"
              leave="ease-in transform duration-200"
              leaveFrom="opacity-100 translate-y-0 sm:scale-100"
              leaveTo="opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
            >
              {/* This element is to trick the browser into centering the modal contents. */}
              <span
                className="hidden sm:inline-block sm:align-middle sm:h-screen"
                aria-hidden="true"
              >
                &#8203;
              </span>
              <div className="inline-block bg-white dark:bg-gray-750 rounded-lg p-4 overflow-hidden shadow-xl transform transition-all sm:align-middle sm:max-w-lg sm:w-full">
                {children}
              </div>
            </Transition.Child>
          </div>
        </div>
      </HDialog>
    </Transition>
  )
}

// frontend-vue/src/components/common/dialog/Dialog.vue
<template>
  <div>
    <slot name="activator" :on="openDialog" />

    <div v-if="open" class="fixed inset-0 z-10 overflow-y-auto">
      <div class="flex items-center justify-center min-h-screen text-center">
        <div class="fixed inset-0" @click.stop.prevent="open = false">
          <div
            class="absolute inset-0 bg-gray-500 opacity-75 dark:bg-gray-900"
          />
        </div>

        <span
          class="hidden sm:inline-block sm:align-middle sm:h-screen"
        />&#8203;

        <slot />
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: 'Dialog',
  props: {
    value: {
      type: Boolean,
      default: false
    }
  },
  data() {
    return {
      open: this.value
    }
  },
  watch: {
    open(val) {
      this.$emit('input', val)
    },
    value(val) {
      this.open = val
    }
  },
  methods: {
    openDialog() {
      this.open = !this.open
    }
  }
}
</script>

<style scoped></style>
