// web/src/components/post/Post.jsx
import React, { useState } from 'react'
import { RiRocketFill } from 'react-icons/ri'
import {
  HiLink,
  HiMenuAlt2,
  HiChatAlt2,
  HiDotsHorizontal,
  HiGlobe,
  HiGlobeAlt,
  HiChevronDown,
  HiChevronUp
} from 'react-icons/hi'
import { Link, useHistory } from 'react-router-dom'
import Tippy from '@tippyjs/react'
import { useDrag } from 'react-dnd'
import { DragItemTypes } from '@/lib/DragItemTypes'
import ReactPlayer from 'react-player'
import { TiPin } from 'react-icons/ti'
import UserAvatar from '@/components/user/UserAvatar'
import PlanetAvatar from '@/components/planet/PlanetAvatar'
import PlanetPopup from '@/components/planet/PlanetPopup'
import UserPopup from '@/components/user/UserPopup'
import { useMutation } from 'urql'

export default function Post({
  postData,
  planet = false,
  embed = false,
  thumbnail = false,
  link = false,
  draggable = false,
  expandable = false,
  actionsLast = false,
  className = ''
}) {
  const [editing, setEditing] = useState(false)
  const [post, setPost] = useState(postData)

  const hasEmbed =
    post.textContent ||
    post.linkUrl ||
    (post.imageUrls && post.imageUrls.length > 0)

  const [{ opacity }, dragRef] = useDrag({
    item: { id: post.id, type: DragItemTypes.POST },
    collect: monitor => ({
      opacity: monitor.isDragging() ? 0.4 : 1
    })
  })

  const [expanded, setExpanded] = useState(false)

  const { push } = useHistory()

  return (
    <article
      ref={draggable ? dragRef : null}
      style={{ opacity }}
      onClick={() => {
        // if (link) push(post.relativeUrl)
      }}
      className={`${className} ${
        link ? 'cursor-pointer' : ''
      } relative transition dark:hover:bg-gray-775 pt-3 px-4 pb-1.5`}
    >
      <div className="flex flex-row-reverse lg:flex-row w-full">
        {thumbnail && <Thumbnail post={post} />}

        <div className="flex-grow">
          <div className="flex flex-wrap items-center text-13 font-medium text-tertiary pb-1">
            {post.pinned && (
              <Tippy content={`Pinned to +${post.planet.name}`}>
                <div className="mr-1.5">
                  <TiPin className="h-5 w-5 text-accent" />
                </div>
              </Tippy>
            )}
            {planet && (
              <>
                <PlanetPopup planet={post.planet}>
                  <PlanetAvatar
                    planet={post.planet}
                    className="h-5 w-5 mr-1.5"
                  />
                </PlanetPopup>
                <PlanetPopup planet={post.planet}>
                  <span className="text-accent hover:underline cursor-pointer">
                    +{post.planet.name}
                  </span>
                </PlanetPopup>
                &nbsp;&middot;&nbsp;
              </>
            )}
            <UserPopup user={post.author}>
              <UserAvatar
                user={post.author}
                className="rounded-full h-5 w-5 mr-1.5 cursor-pointer"
              />
            </UserPopup>
            <UserPopup user={post.author}>
              <span className="hover:underline cursor-pointer">
                {post.author.username}
              </span>
            </UserPopup>
            &nbsp;&middot;&nbsp;
            <Tippy content={post.timeSinceFull}>
              <span>{post.timeSince}</span>
            </Tippy>
            &nbsp;&middot; ({post.linkUrl && post.domain}
            {!post.linkUrl &&
              post.imageUrls &&
              post.imageUrls.length > 0 &&
              'image post'}
            {!post.linkUrl &&
              (!post.imageUrls || post.imageUrls.length === 0) &&
              'text post'}
            )
          </div>
          <Link to={post.relativeUrl} className="text-secondary text-base">
            {post.title || post?.meta?.title || '(untitled)'}
          </Link>

          {!actionsLast && (
            <div className="hidden lg:block pt-0.5 -ml-2">
              <Actions
                {...{
                  post,
                  setPost,
                  expanded,
                  setExpanded,
                  hasEmbed,
                  expandable
                }}
              />
            </div>
          )}
        </div>
      </div>

      {!actionsLast && (
        <div className="block lg:hidden pt-2 -mr-2">
          <Actions
            {...{ post, setPost, expanded, setExpanded, hasEmbed, expandable }}
          />
        </div>
      )}

      {hasEmbed && (embed || expanded) && <Embed post={post} />}

      {actionsLast && (
        <div className="-mr-2 lg:-ml-2">
          <Actions
            {...{ post, setPost, expanded, setExpanded, hasEmbed, expandable }}
          />
        </div>
      )}
    </article>
  )
}

function Embed({ post }) {
  return (
    <div className="py-2 space-y-2 flex flex-col lg:max-w-screen-sm">
      {post.linkUrl && (
        <>
          {ReactPlayer.canPlay(post.linkUrl) ? (
            <div className="aspect-h-9 aspect-w-16 ">
              <ReactPlayer
                className="react-player"
                url={post.linkUrl}
                width="100%"
                height="100%"
              />
            </div>
          ) : (
            <>
              {post.meta && post.meta.title ? (
                <a
                  to={post.linkUrl}
                  target="_blank"
                  rel="noreferrer noopener nofollow"
                  className="mt-2 block rounded-md border dark:border-gray-700 transition"
                  onClick={e => e.stopPropagation()}
                >
                  <div className="flex items-start">
                    <div className="w-24 h-24 relative flex-shrink-0 rounded-l-md">
                      {post.thumbnailUrl || post.logoUrl ? (
                        <img
                          src={post.thumbnailUrl || post.logoUrl}
                          className="rounded-l-md object-cover h-full w-full"
                        />
                      ) : (
                        <div className="flex w-24 h-24 rounded-l-md border-r border-gray-200 dark:border-gray-800">
                          <HiLink className="w-8 h-8 m-auto text-tertiary" />
                        </div>
                      )}
                    </div>

                    <div
                      className={`flex flex-col px-3 py-2 cursor-pointer h-24`}
                    >
                      <div className="font-medium line-clamp-1 text-secondary text-base">
                        {post.meta && post.meta.title
                          ? post.meta.title
                          : post.linkUrl}
                      </div>

                      <div className="text-xs font-medium text-tertiary line-clamp-1 mt-1">
                        {post.meta && post.meta.description
                          ? post.meta.description
                          : ''}
                      </div>

                      <div className="mt-auto flex items-center pt-3">
                        {post.logoUrl && (
                          <div className="inline-block w-4 h-4 mr-3">
                            <img
                              alt={post.domain}
                              src={post.logoUrl}
                              className="w-4 h-4 object-cover"
                            />
                          </div>
                        )}
                        <div className="inline-block text-tertiary text-xs line-clamp-1">
                          {post.domain}
                        </div>
                      </div>
                    </div>
                  </div>
                </a>
              ) : (
                <a
                  to={post.linkUrl}
                  rel="noopener noreferrer nofollow"
                  target="_blank"
                  className="text-sm text-accent cursor-pointer hover:underline border dark:border-gray-700 p-2.5 rounded-md"
                >
                  {post.linkUrl}
                </a>
              )}
            </>
          )}
        </>
      )}

      {post.imageUrls.length > 0 && (
        <div className="relative max-w-screen-sm">
          <img src={post.imageUrls[0]} className="object-cover w-full h-full" />
        </div>
      )}

      {post.textContent && (
        <div
          dangerouslySetInnerHTML={{ __html: post.textContent }}
          className="prose prose-sm dark:prose-dark max-w-none border dark:border-gray-700 p-2.5 rounded-md"
        />
      )}
    </div>
  )
}

function Actions({
  post,
  setPost,
  expanded,
  setExpanded,
  hasEmbed,
  expandable
}) {
  return (
    <div className="space-x-1 flex items-center justify-items-end lg:justify-start flex-row-reverse lg:flex-row">
      <Rocket post={post} setPost={setPost} />
      <CommentCount post={post} />
      {expandable && hasEmbed && <Expand {...{ expanded, setExpanded }} />}
      <Options post={post} />
    </div>
  )
}

function Rocket({ post, setPost }) {
  const [rocket] = useMutation(ROCKET_POST_MUTATION)
  const [unrocket] = useMutation(UNROCKET_POST_MUTATION)

  const rocketVariables = { postId: post.id }
  const toggleRocket = () => {
    if (post.isRocketed) unrocket.mutate(rocketVariables)
    else rocket.mutate(rocketVariables)
  }

  return (
    <div
      onClick={e => {
        e.stopPropagation()
        toggleRocket()
      }}
      className={`action-chip ${
        post.isRocketed ? 'text-red-400' : 'text-tertiary'
      }`}
    >
      <RiRocketFill className="w-4 h-4" />
      <div className="ml-1.5">{post.rocketCount}</div>
    </div>
  )
}

function CommentCount({ post }) {
  return (
    <Link to={post.relativeUrl} className={`action-chip text-tertiary`}>
      <HiChatAlt2 className="w-5 h-5 mr-1.5" />
      {post.commentCount}
    </Link>
  )
}

function Expand({ expanded, setExpanded }) {
  return (
    <Tippy
      placement="right"
      content={expanded ? 'Hide Details' : 'Show Details'}
    >
      <div
        className={`mr-1.5 p-1 inline-block items-center cursor-pointer rounded-full hover:bg-gray-200 dark:hover:bg-gray-700 transition text-tertiary`}
        onClick={e => {
          e.stopPropagation()
          e.preventDefault()
          setExpanded(!expanded)
        }}
      >
        {expanded ? (
          <HiChevronUp className="w-5 h-5" />
        ) : (
          <HiChevronDown className="w-5 h-5" />
        )}
      </div>
    </Tippy>
  )
}

function Options({ post }) {
  return (
    <div className="inline-flex items-center cursor-pointer text-mid p-1 rounded-full hover:bg-gray-200 dark:hover:bg-gray-700 transition">
      <HiDotsHorizontal className="w-5 h-5" />
    </div>
  )
}

function Thumbnail({ post }) {
  return (
    <div className="pl-4 lg:pl-0 lg:pr-4">
      <div className={`relative w-14 h-14 lg:w-24 lg:h-16 flex-shrink-0`}>
        <div
          className="h-full w-full rounded dark:bg-gray-650 bg-gray-200 inline-flex items-center justify-center text-tertiary bg-cover bg-center bg-no-repeat"
          style={
            post.thumbnailUrl || post.logoUrl
              ? {
                  backgroundImage: `url(${post.thumbnailUrl || post.logoUrl})`
                }
              : {}
          }
        >
          {!(post.thumbnailUrl || post.logoUrl) &&
            (post.linkUrl ? (
              <HiGlobeAlt className="w-8 h-8" />
            ) : (
              <HiMenuAlt2 className="w-8 h-8" />
            ))}
        </div>
      </div>
    </div>
  )
}

// frontend/src/components/page_components/home/Post.vue
<template>
  <article>
    <div class="post">
      <div class="post__top">
        <nuxt-link :to="`/@${post.author.username}`">
          <img :src="post.author.profile.avatarURL" class="object-cover object-center w-8 h-8 rounded-full bg-gray-200">
        </nuxt-link>
        <div class="flex flex-col ml-4 pr-12 flex-grow">
          <div class="text-xs">
            <nuxt-link :to="`/@${post.author.username}`" class="text-tertiary font-semibold hover:underline">
              {{ post.author.username }}
            </nuxt-link>
            <span class="text-tertiary">in</span>
            <nuxt-link :to="`/+${post.planet.name}`" class="text-accent font-semibold hover:underline">
              +{{ post.planet.name }}
            </nuxt-link>
          </div>
          <div class="text-xs mt-0.5">
            <span class="text-tertiary">{{ post.timeSince }} &middot; </span>
            <nuxt-link :to="post.relativeURL" class="text-tertiary hover:underline">
              {{ post.commentCount }} comment{{ post.commentCount === 1 ? '' : 's' }}
            </nuxt-link>
          </div>
        </div>
        <!--        <div class="post__bookmark">
          <iconify-icon icon="bookmark-outline" class="w-4 h-4" />
        </div>-->
      </div>
      <div class="post__content">
        <div class="text-base text-primary font-semibold">
          {{ post.title }}
        </div>
        <div v-if="post.textContent" class="text-primary line-clamp-3 text-sm mt-1" v-html="post.textContent" />

        <img v-if="post.imageURLs && post.imageURLs.length > 0" :src="post.imageURLs[0]" class="border border-gray-200 bg-gray-100 hover:bg-gray-200 transition duration-100 ease-in-out mt-4 object-contain object-center max-w-full w-full h-32 rounded-2xl" @click.stop.prevent="$store.dispatch('openImageDialog', post.imageURLs)">

        <!--        <a
          v-else-if="post.embed && post.embed.links && post.embed.links.thumbnail && post.embed.links.thumbnail.length > 0"
          :href="post.linkURL"
          target="_blank"
          rel="noreferrer noopener nofollow"
          class="rounded-2xl mt-4 border border-gray-200 bg-gray-100 hover:bg-gray-200 transition duration-100 ease-in-out block"
        >
          <img :src="post.embed.links.thumbnail[0].href" class="bg-white object-contain object-center max-w-full w-full h-auto rounded-t-2xl" style="max-height: 19.8125rem">
          <div class="rounded-b-xl px-4 py-3 cursor-pointer">
            <div class="text-sm text-secondary font-semibold">
              {{ post.embed.meta.title }}
            </div>

            <div class="text-xs text-tertiary font-medium line-clamp-2 mt-0.5">
              {{ post.embed.meta.description }}
            </div>

            <div class="text-xs mt-1 font-semibold text-tertiary">
              {{ post.domain }}
            </div>
          </div>
        </a>-->
        <a
          v-else-if="post.embed && post.embed.links && post.embed.links.thumbnail && post.embed.links.thumbnail.length > 0"
          :href="post.linkURL"
          target="_blank"
          rel="noreferrer noopener nofollow"
          class="rounded-lg mt-4 border border-gray-200 bg-gray-100 hover:bg-gray-200 transition duration-100 ease-in-out items-start flex flex-row"
        >
          <img :src="post.embed.links.thumbnail[0].href" class="rounded-l-lg bg-white object-cover object-center h-32 w-32">
          <div class="px-6 py-3 cursor-pointer flex flex-col h-32">
            <div class="text-sm text-secondary font-semibold line-clamp-2">
              {{ post.embed.meta.title }}
            </div>

            <div class="text-xs text-tertiary font-medium line-clamp-2 mt-1">
              {{ post.embed.meta.description }}
            </div>

            <div class="flex flex-row items-start mt-auto">
              <img v-if="post.embed.links.icon && post.embed.links.icon.length > 0" :src="post.embed.links.icon[0].href" class="w-4 h-4 mr-3 object-contain rounded-sm">
              <div class="text-xs font-semibold text-tertiary">
                {{ post.domain }}
              </div>
            </div>

          </div>
        </a>
      </div>
      <div class="post__bottom">
        <div class="post__chip">
          <!--          <svg class="w-5 h-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
            <path fill-rule="evenodd" d="M3.172 5.172a4 4 0 015.656 0L10 6.343l1.172-1.171a4 4 0 115.656 5.656L10 17.657l-6.828-6.829a4 4 0 010-5.656z" clip-rule="evenodd" />
          </svg>-->
          <svg class="w-4 h-4" fill="currentColor" version="1.1" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
            <path d="m17.415 15.791s0-4.0376 0.0014-5.4164c0-4.3317-5.4164-7.5816-5.4164-7.5816s-5.4164 3.2499-5.4157 7.5823c0 3.2385 0.036062 5.4327 0.036062 5.4327s-3.2859 2.1489-3.2859 5.3988h17.331c0-3.2499-3.2506-5.4157-3.2506-5.4157zm-7.4154-5.2913c-9.404e-4 -1.1048 0.89494-2.0007 1.9997-1.9997 1.7821-2.829e-4 2.6744 2.1542 1.4144 3.4141-1.26 1.26-3.4144 0.36762-3.4141-1.4144z" />
          </svg>
          <span class="font-semibold ml-2 text-xs">{{ post.rocketCount }}</span>
        </div>

        <div class="ml-4 post__chip">
          <iconify-icon icon="comment" class="w-4 h-4" />
          <span class="font-semibold ml-2 text-xs">{{ post.commentCount }}</span>
        </div>

        <div class="ml-auto px-3 py-1 text-tertiary inline-flex flex-row items-center rounded-full hover:bg-gray-200 transition duration-150 ease-in-out">
          <iconify-icon icon="share" class="w-4 h-4 text-green-500" />
          <!--          <span class="ml-4 text-xs font-semibold text-green-500">Share</span>-->
        </div>

        <div class="ml-4 px-3 py-1 text-tertiary inline-flex flex-row items-center rounded-full hover:bg-gray-200 transition duration-150 ease-in-out">
          <iconify-icon icon="bookmark-outline" class="w-4 h-4" />
          <!--          <span class="ml-4 text-xs font-semibold text-green-500">Share</span>-->
        </div>

        <!--        <div class="post__options">
          <iconify-icon icon="dots" class="w-4 h-4" />
        </div>-->
      </div>
    </div>
  </article>
</template>

<script>
import IconifyIcon from '@iconify/vue'
import dots from '@iconify/icons-heroicons-solid/dots-horizontal'
import comment from '@iconify/icons-heroicons-solid/annotation'
import share from '@iconify/icons-heroicons-solid/share'
import bookmarkOutline from '@iconify/icons-fa-regular/bookmark'
import bookmark from '@iconify/icons-fa-solid/bookmark'

IconifyIcon.addIcon('dots', dots)
IconifyIcon.addIcon('comment', comment)
IconifyIcon.addIcon('share', share)
IconifyIcon.addIcon('bookmark-outline', bookmarkOutline)
IconifyIcon.addIcon('bookmark', bookmark)

export default {
  name: 'Post',
  props: {
    post: {
      type: Object,
      required: true
    }
  }
}
</script>

<style scoped lang="scss">
.post {
  @apply bg-white border border-gray-100 shadow sm:rounded-xl pb-6 cursor-pointer;

  &__top {
    @apply pt-5 pl-5 pr-5 sm:pt-6 sm:pl-8 sm:pr-20 flex flex-row;
  }

  &__content {
    @apply px-5 sm:pl-20 sm:pr-20 mt-3;
  }

  &__bottom {
    @apply sm:mt-4 mt-5 sm:pl-20 sm:pr-20 pl-5 pr-20 flex flex-row items-center;
  }

  &__chip {
    @apply px-3 py-1 text-gray-500 inline-flex flex-row items-center rounded-full border border-gray-200 hover:bg-gray-200 transition duration-150 ease-in-out;
  }

  &__bookmark {
    @apply ml-auto px-3 py-1 text-gray-500 inline-flex flex-row items-center rounded-full hover:bg-gray-200 transition duration-150 ease-in-out opacity-0 transition duration-150 ease-in-out;
  }

  &__options {
    @apply cursor-pointer ml-auto px-3 py-1 text-gray-500 inline-flex flex-row items-center rounded-full hover:bg-gray-200 transition duration-150 ease-in-out opacity-0;
  }
}

.post:hover > .post__top > .post__bookmark {
  @apply opacity-100;
}

.post:hover > .post__bottom > .post__options {
  @apply opacity-100;
}
</style>
