// frontend/src/components/common/dialog/Dialog.vue
<template>
  <div>
    <slot name="activator" :on="openDialog" />

    <div v-if="open" class="fixed inset-0 z-10 overflow-y-auto">
      <div class="flex items-center justify-center min-h-screen text-center">
        <div class="fixed inset-0" @click.stop.prevent="open = false">
          <div
            class="absolute inset-0 bg-gray-500 opacity-75 dark:bg-gray-900"
          />
        </div>

        <span
          class="hidden sm:inline-block sm:align-middle sm:h-screen"
        />&#8203;

        <slot />
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: 'Dialog',
  props: {
    value: {
      type: Boolean,
      default: false
    }
  },
  data () {
    return {
      open: this.value
    }
  },
  watch: {
    open (val) {
      this.$emit('input', val)
    },
    value (val) {
      this.open = val
    }
  },
  methods: {
    openDialog () {
      this.open = !this.open
    }
  }
}
</script>

<style scoped></style>

// web/src/components/ui/dialog/Dialog.jsx
import { Fragment } from 'react'
import { Dialog as HeadlessDialog, Transition } from '@headlessui/react'

export default function Dialog({
  isOpen,
  close,
  children,
  closeOnOverlayClick = false
}) {
  return (
    <Transition show={isOpen} as={Fragment}>
      <HeadlessDialog open={isOpen} onClose={close} static>
        <div className="fixed z-10 inset-0 overflow-y-auto">
          <div className="flex items-end justify-center min-h-screen pt-4 px-4 pb-20 text-center sm:block sm:p-0">
            <Transition.Child
              enter="ease-out duration-150"
              enterFrom="opacity-0"
              enterTo="opacity-100"
              leave="ease-in duration-150"
              leaveFrom="opacity-100"
              leaveTo="opacity-0"
            >
              <HeadlessDialog.Overlay className="fixed inset-0 transition-opacity">
                <div className="absolute inset-0 bg-gray-500 dark:bg-black opacity-75" />
              </HeadlessDialog.Overlay>
            </Transition.Child>

            <Transition.Child
              enter="ease-out transform duration-150"
              enterFrom="opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
              enterTo="opacity-100 translate-y-0 sm:scale-100"
              leave="ease-in transform duration-150"
              leaveFrom="opacity-100 translate-y-0 sm:scale-100"
              leaveTo="opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
            >
              {/* This element is to trick the browser into centering the modal contents. */}
              <span
                className="hidden sm:inline-block sm:align-middle sm:h-screen"
                aria-hidden="true"
              >
                &#8203;
              </span>
              <div
                onClick={() => {
                  if (closeOnOverlayClick) close()
                }}
                className="inline-block h-screen overflow-hidden transform transition-all align-middle w-full"
              >
                <div className="flex h-full w-full items-center justify-center">
                  {children}
                </div>
              </div>
            </Transition.Child>
          </div>
        </div>
      </HeadlessDialog>
    </Transition>
  )
}
