// web/src/components/LoginDialog.jsx
import { useLoginDialog } from '@/hooks/useLoginDialog'
import { useForm } from 'react-hook-form'
import { useCreateAccountMutation, useLoginMutation } from '@/graphql/hooks'
import {
  IconEmail,
  IconSpinner,
  IconUser,
  IconUserToServerArrow,
  IconX
} from '@/components/ui/icons/Icons'
import { useState } from 'react'
import { VectorLogo } from '@/components/ui/vectors'
import isEmail from 'validator/es/lib/isEmail'
import StyledDialog from '@/components/ui/dialog/StyledDialog'
import ShowPasswordButton from '@/components/ui/ShowPasswordButton'

const usernameRegex = /^[A-Za-z0-9-_]+$/gi

export default function LoginDialog() {
  const [open, setOpen, isCreateAccount, setCreateAccount] = useLoginDialog()
  const [showPassword, setShowPassword] = useState(false)
  const {
    handleSubmit,
    register,
    watch,
    reset,
    getValues,
    formState: { errors }
  } = useForm({
    mode: 'onChange',
    shouldUnregister: true
  })
  const email = watch('email')
  const username = watch('username')
  const usernameOrEmail = watch('usernameOrEmail')
  const password = watch('password')
  const confirmPassword = watch('confirmPassword')
  const [createAccount, { loading: createAccountLoading }] =
    useCreateAccountMutation()
  const [login, { loading: loginLoading }] = useLoginMutation()
  const onSubmit = ({ usernameOrEmail, email, username, password }) => {
    if (isCreateAccount) {
      createAccount({
        variables: {
          input: {
            username,
            password,
            email: email ? email : null
          }
        }
      }).then(
        ({
          data: {
            createAccount: { accessToken, user }
          }
        }) => {
          localStorage.setItem('token', accessToken)
          location.reload()
        }
      )
    } else {
      const input = isEmail(usernameOrEmail)
        ? { email: usernameOrEmail }
        : { username: usernameOrEmail }
      login({ variables: { input: { ...input, password } } }).then(
        ({
          data: {
            login: { accessToken, user }
          }
        }) => {
          localStorage.setItem('token', accessToken)
          location.reload()
        }
      )
    }
  }
  const close = () => {
    reset()
    setOpen(false)
  }
  const disabled = !(isCreateAccount
    ? !!username &&
      username.length >= 3 &&
      username.length <= 20 &&
      usernameRegex.test(username) &&
      (!email || (!!email && isEmail(email))) &&
      !!password &&
      password.length >= 6 &&
      !!confirmPassword &&
      confirmPassword === password
    : !!usernameOrEmail && !!password)

  return (
    <StyledDialog
      close={close}
      open={open}
      onSubmit={handleSubmit(onSubmit)}
      buttons={
        <button
          type="submit"
          className={`form-button-submit`}
          disabled={disabled}
        >
          {(isCreateAccount && createAccountLoading) ||
          (!isCreateAccount && loginLoading) ? (
            <IconSpinner className="w-5 h-5" />
          ) : (
            <IconUserToServerArrow className="w-5 h-5" />
          )}
        </button>
      }
    >
      <div className="rounded-t-lg bg-gradient-to-r from-red-400 to-indigo-600 h-2" />
      <div className="px-5 pt-2 pb-9 text-left">
        <div className="pb-4 flex items-center">
          <div
            onClick={() => {
              if (isCreateAccount) {
                setCreateAccount(false)
                reset()
              }
            }}
            className={`text-sm cursor-pointer mr-3 py-3 border-b-2 inline-flex items-center justify-center px-3 ${
              isCreateAccount
                ? 'border-transparent text-secondary'
                : 'dark:border-gray-300 text-primary'
            }`}
          >
            Log In
          </div>

          <div
            onClick={() => {
              if (!isCreateAccount) {
                setCreateAccount(true)
                reset()
              }
            }}
            className={`text-sm cursor-pointer py-3 border-b-2 inline-flex items-center justify-center px-3 ${
              isCreateAccount
                ? 'dark:border-gray-300 text-primary'
                : 'border-transparent text-secondary'
            }`}
          >
            Create Account
          </div>

          <div className="ml-auto">
            <VectorLogo className="h-3.5 text-secondary" />
          </div>
          <IconX
            className="ml-5 w-5 h-5 text-tertiary highlightable"
            onClick={() => close()}
          />
        </div>

        <div className="space-y-4">
          {isCreateAccount ? (
            <>
              <div>
                <div className="relative">
                  <input
                    id="username"
                    {...register('username', {
                      required: true,
                      pattern: usernameRegex,
                      maxLength: 20,
                      minLength: 3
                    })}
                    className={`form-input-icon`}
                    placeholder="Username"
                    minLength={3}
                    maxLength={20}
                  />
                  <IconUser className={`form-input-icon-icon`} />
                </div>
                {errors.username?.type === 'minLength' && (
                  <div className={`form-error`}>
                    Username must be between 3 and 20 characters
                  </div>
                )}
                {errors.username?.type === 'pattern' && (
                  <div className={`form-error`}>
                    Letters, numbers, dashes, and underscores only
                  </div>
                )}
              </div>

              <div>
                <div className="relative">
                  <input
                    id="email"
                    {...register('email', {
                      validate: {
                        email: value =>
                          !value || isEmail(value) || 'Invalid email'
                      }
                    })}
                    className={`form-input-icon`}
                    placeholder="Email (Optional)"
                    type="email"
                  />
                  <IconEmail className={`form-input-icon-icon`} />
                </div>
                {errors.email?.type === 'email' && (
                  <div className={`form-error`}>{errors.email.message}</div>
                )}
              </div>
            </>
          ) : (
            <input
              id="usernameOrEmail"
              {...register('usernameOrEmail', {
                shouldUnregister: true
              })}
              className={`form-input`}
              placeholder="Username or email"
            />
          )}

          {isCreateAccount ? (
            <>
              <div>
                <div className="relative">
                  <input
                    id="password"
                    {...register('password', {
                      required: true,
                      minLength: 6
                    })}
                    className={`form-input-password`}
                    placeholder="Password"
                    type={showPassword ? 'text' : 'password'}
                    minLength={6}
                  />
                  <ShowPasswordButton
                    showPassword={showPassword}
                    setShowPassword={setShowPassword}
                  />
                </div>
                {errors.password?.type === 'minLength' && (
                  <div className={`form-error`}>
                    Password must be at least 6 characters
                  </div>
                )}
              </div>

              <div>
                <div className="relative">
                  <input
                    id="confirmPassword"
                    {...register('confirmPassword', {
                      required: true,
                      validate: {
                        matchesPreviousPassword: value => {
                          const { password } = getValues()
                          return password === value || 'Passwords do not match'
                        }
                      }
                    })}
                    className={`form-input-password`}
                    placeholder="Confirm Password"
                    type={showPassword ? 'text' : 'password'}
                  />
                  <ShowPasswordButton
                    showPassword={showPassword}
                    setShowPassword={setShowPassword}
                  />
                </div>
                {!!password &&
                  !!confirmPassword &&
                  password !== confirmPassword && (
                    <div className={`form-error`}>Passwords do not match</div>
                  )}
              </div>
            </>
          ) : (
            <div className="relative">
              <input
                id="password"
                {...register('password', { required: true })}
                className={`form-input`}
                placeholder="Password"
                type={showPassword ? 'text' : 'password'}
              />
              <ShowPasswordButton
                showPassword={showPassword}
                setShowPassword={setShowPassword}
              />
            </div>
          )}
        </div>
      </div>
    </StyledDialog>
  )
}

// frontend/src/components/dialogs/LoginDialog.vue
<template>
  <Dialog v-model="open">
    <template v-slot:activator="{ on }">
      <div class="inline-flex flex-row items-center ml-auto">
        <button
          class="px-3 py-1 mr-3 text-sm text-indigo-500 border border-indigo-500 rounded"
          @click="openLogIn(on)"
        >
          Log In
        </button>
        <button
          class="px-3 py-1 text-sm text-white bg-indigo-500 rounded"
          @click="openSignUp(on)"
        >
          Sign Up
        </button>
      </div>
    </template>

    <DialogCard>
      <div class="p-6">
        <Icon name="comet-logo" class="h-6 mb-3" />
        <!--<div class="mb-6 text-sm tracking-wide uppercase text-secondary">
          <span
            :class="{ 'font-semibold': tab === 0 }"
            class="cursor-pointer hover:underline"
            @click="tab = 0"
            >Log In</span
          >
          <span class="text-secondary">/</span>
          <span
            :class="{ 'font-semibold': tab === 1 }"
            class="cursor-pointer hover:underline"
            @click="tab = 1"
            >Sign Up</span
          >
        </div>-->
        <form v-on="tab === 0 ? { submit: logIn } : { submit: signUp }">
          <TextInput
            v-model="username"
            label="Username"
            placeholder="Username"
            error-message="Username must be 3-15 characters and use characters A-Z, 1-9, -, _"
            :error="!usernameValid && tab === 1"
          />
          <TextInput
            v-show="tab === 1"
            v-model="email"
            label="Email (Optional)"
            placeholder="Email (Optional)"
            error-message="Please enter a valid email address."
            :error="!emailValid"
          />
          <TextInput
            v-model="password"
            label="Password"
            placeholder="******************"
            error-message="Password must be at least 6 characters."
            :error="!passwordValid && tab === 1"
            type="password"
          />
          <TextInput
            v-show="tab === 1"
            v-model="confirmPassword"
            label="Confirm Password"
            placeholder="******************"
            error-message="Passwords do not match."
            :error="!confirmPasswordValid"
            type="password"
          />
          <div class="flex items-center justify-between pt-3">
            <button
              type="submit"
              :class="formValid ? 'text-white' : 'text-secondary opacity-25'"
              :disabled="!formValid"
              class="inline-flex items-center px-4 py-2 leading-6 text-gray-300 transition duration-150 ease-in-out bg-gray-300 rounded focus:outline-none dark:bg-gray-800"
            >
              <div v-show="loading" class="mr-3 -ml-1">
                <Icon name="spinner" />
              </div>
              {{ tab === 0 ? 'Log In' : 'Sign Up' }}
            </button>

            <button
              type="button"
              class="inline-flex items-center px-4 py-2 text-sm leading-6 transition duration-150 ease-in-out rounded text-secondary focus:outline-none"
              @click="switchTab"
            >
              {{ tab === 0 ? 'Create an account' : 'Already have an account' }}
            </button>

            <!--<a
              class="inline-block text-sm font-bold text-indigo-500 align-baseline hover:text-indigo-800"
              href="#"
            >
              Forgot Password?
            </a>-->
          </div>
          <div v-show="tab === 1" class="pt-5 text-xs text-secondary">
            By clicking Sign Up, you agree to our
            <nuxt-link to="/terms" class="text-indigo-500">
              Terms of Service
            </nuxt-link>
            and
            <nuxt-link to="/privacy" class="text-indigo-500">
              Privacy Policy
            </nuxt-link>.
          </div>
        </form>
      </div>
    </DialogCard>
  </Dialog>
</template>

<script>
import * as EmailValidator from 'email-validator'
import loginGql from '@/gql/login'
import signUpGql from '@/gql/signUp'

export default {
  name: 'LoginDialog',
  data () {
    return {
      open: false,
      tab: 0,
      username: null,
      email: null,
      password: null,
      confirmPassword: null,
      loading: false
    }
  },
  computed: {
    usernameValid () {
      const u = this.username
      return (
        !u ||
        (u && u.length >= 3 && u.length <= 15 && u.match(/^[a-zA-Z0-9_]+$/))
      )
    },
    emailValid () {
      const e = this.email
      return !e || (e && EmailValidator.validate(e))
    },
    passwordValid () {
      const p = this.password
      return !p || (p && p.length >= 6)
    },
    confirmPasswordValid () {
      return !this.confirmPassword || this.password === this.confirmPassword
    },
    formValid () {
      if (this.tab === 0) {
        return this.username && this.password
      } else {
        return (
          this.username &&
          this.usernameValid &&
          this.emailValid &&
          this.password &&
          this.passwordValid &&
          this.confirmPassword &&
          this.confirmPasswordValid
        )
      }
    }
  },
  methods: {
    switchTab () {
      if (this.tab === 0) { this.tab = 1 } else { this.tab = 0 }
    },
    openLogIn (on) {
      this.tab = 0
      on()
    },
    openSignUp (on) {
      this.tab = 1
      on()
    },
    async logIn (e) {
      e.preventDefault()
      this.loading = true
      try {
        const res = await this.$apollo
          .mutate({
            mutation: loginGql,
            variables: {
              username: this.username,
              password: this.password
            }
          })
          .then(({ data }) => data && data.login)
        await this.$apolloHelpers.onLogin(res.accessToken)
        await this.$store.dispatch('fetchCurrentUser')
        this.open = false
      } catch (e) {
        this.$toast.error(e.message.split('GraphQL error: ')[1])
      }
      this.loading = false
    },
    async signUp (e) {
      e.preventDefault()
      if (!this.formValid) { return }
      this.loading = true
      try {
        const res = await this.$apollo
          .mutate({
            mutation: signUpGql,
            variables: {
              username: this.username,
              password: this.password,
              email: this.email
            }
          })
          .then(({ data }) => data && data.signUp)
        await this.$apolloHelpers.onLogin(res.accessToken)
        await this.$store.dispatch('fetchCurrentUser')
        this.open = false
      } catch (e) {
        this.$toast.error(e.message.split('GraphQL error: ')[1])
      }
      this.loading = false
    }
  }
}
</script>

<style scoped></style>
